### PR TITLE
Drop support for net7, upgrade dependencies

### PR DESCRIPTION
**Pull request by Vogel612**
Also updates documentation on README to accurately remove net5.0 support implication. Mentions planned dropping of net6 support and planned net9 support.

### CODE REVIEW

**Comment by Rwing** [comment]
We'd better support .NET 9 when releasing the new version, so I will merge the PR first and wait until .NET 9 is supported before publishing the new version.

**Comment by Rwing** [comment]
Thank you very much, I have already released the new version.

**Comment by Vogel612** [comment]
@Rwing sorry, that's on me... this utterly breaks for statements where the Limit and Offset are not applied to the top-level SelectExpression because I made an incorrect change. 0.7.0 should be considered broken and unusable... I am currently working on a fix for the changed net9 paradigm. In the meantime I strongly recommend rolling this back and unpublishing from nuget

**Comment by Rwing** [comment]
Sorry for my late reply. Has the bug been resolved now? Does the issue only affect the .NET 8 version?

**Pull request merged**
